# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
#

development:
  secret_key_base: 0ef51915abfcd1dcfe8b65308c0634be17f6be7b2522fa134d8ed4f7d1bb8baf4cad2f28cc634b9d83fc74b08471dbfe4540278a3078ed2e0d154cb87597fd7c
  SENDGRID_USERNAME: photo_app_seb 
  SENDGRID_PASSWORD:  Ph0t0@pp

  # STRIPE_TEST_PUBLISHABLE_KEY: sk_test_Tr0p7tJaWVJlaFCnIB49N4Om
  # STRIPE_TEST_SECRET_KEY: pk_test_SLXMMP63Fmv3nuhFs4fJ75II

test:
  secret_key_base: 1c969a087974223a75fdf8e485aad5ab9421ebb1ae7f5522387bf14347b26412a23bbd0918d48a7f3a62cb007c5ac0d87bcc1b4da3603a1d5e8c9b9bcba711d1
  SENDGRID_USERNAME: photo_app_seb 
  SENDGRID_PASSWORD:  Ph0t0@pp

  # STRIPE_TEST_PUBLISHABLE_KEY: sk_test_Tr0p7tJaWVJlaFCnIB49N4Om
  # STRIPE_TEST_SECRET_KEY: pk_test_SLXMMP63Fmv3nuhFs4fJ75II

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  SENDGRID_USERNAME: photo_app_seb 
  SENDGRID_PASSWORD:  Ph0t0@pp

  # STRIP_API_KEY: sk_live_wLwa3zc9iU2fpxvs0fa3t0Hz
  # STRIPE_API_SECRET: pk_live_yIiiD1H1IvjHim2oaAVuebx6